doc-warnings: no
test-warnings: no
strictness: medium
max-line-length: 80

ignore-paths:
    - doc
    - src/pkglts_data
    - test
#ignore-patterns:
#    - ^example/doc_.*\.py$
#    - (^|/)docs(/|$)
