# {# pkglts, travis
# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.5"
# #}

# {# pkglts, travis.addons
addons:
  apt:
    packages:
# #}

# {# pkglts, travis.install
install:
 - pip install -r requirements.txt
 - pip install -r dvlpt_requirements.txt
 - pip install coveralls
# #}

# {# pkglts, travis.script
script:
 - nosetests
# #}

# {# pkglts, travis.after
after_success:
  - coveralls
# #}
# blacklist
branches:
  except:
    - wip_*
