# {# pkglts, travis
# Config file for automatic testing at travis-ci.org

language: python

python:
{%- for pyver in pysetup.intended_versions %}
  - "{{ pyver[0] }}.{{ pyver[1] }}"
{%- endfor %}
# #}

addons:
  apt:
    packages:
# {# pkglts, travis.addons
# #}

install:
# {# pkglts, travis.install
 - pip install -r requirements.txt
 - pip install -r dvlpt_requirements.txt
{%- if 'coveralls' is available %}
 - pip install coveralls
{%- endif %}
# #}

script:
# {# pkglts, travis.script
 - nosetests
# #}

after_success:
# {# pkglts, travis.after
{%- if 'coveralls' is available -%}
  - coveralls
{%- endif %}
# #}
