package:
  name: pkglts
  version: "1.0.0"

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  summary: "Building packages with long term support"
  license: "CeCILL-C"
  license_file: LICENSE
